name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      name: CI

on:
  push:
    branches: [main]

jobs: 
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - uses: max/secret-scan@master

  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2   
      
      - run: |
          mkdir -p logs/
      - name: Safety
        run: |
         pip install safety
         safety check -r Environment/App/app/flask/requirements.txt > logs/result-safety.txt
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result.txt   
          

      - name: Pyraider
        run: |
          pip install pyraider
          pyraider check -f Environment/App/app/flask/requirements.txt > logs/result-pyraider.txt
          
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result.json 
      - name: Build docker-compose
        run: docker-compose -f ./Environment/App/docker-compose.yml up --build -d
        
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
        
      - run: |
          mkdir -p logs/
          echo 'Environment/App/db' > logs/exclude.txt
      
      
      - uses: max/secret-scan@master
        with:
          exclude_path: 'logs/exclude.txt'
  
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2   
      
      - run: |
          mkdir -p logs/
      - name: Safety
        run: |
         pip install safety
         safety check -r ./Environment/App/app/flask/requirements.txt > logs/result.txt
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result.txt   
          
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result.json 
  
  test:
    needs: [build, sca]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Image for testing
        run: docker-compose -f ./Environment/App/docker-compose.yml up --build -d 
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Tests/requirements.txt
        
      
          
  sast:
    needs: [build, sca]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
        
      - run: |
          mkdir -p logs/      
      
      - uses: jpetrucciani/bandit-check@master
        with:
          path: '.'
          bandit_flags: '-lll -o logs/output.json -f json'
    
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/output.json
